# Generated by Django 4.0.6 on 2024-03-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(max_length=20)),
                ('twilio_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('message_sid', models.CharField(max_length=255)),
                ('num_media', models.IntegerField(default=0)),
            ],
        ),
    ]
