# Generated by Django 4.0.6 on 2024-02-23 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField()),
                ('description', models.TextField()),
                ('qtyperpcs', models.IntegerField()),
                ('bccs', models.TextField()),
                ('bcib', models.TextField()),
                ('bcpcs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField()),
                ('child_sku', models.TextField()),
                ('mech_per_pcs', models.IntegerField()),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='promo_calculator.product')),
            ],
        ),
    ]
